# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui.ui'
#
# Created: Mon May 28 18:50:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(697, 453)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.IPLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPLineEdit.sizePolicy().hasHeightForWidth())
        self.IPLineEdit.setSizePolicy(sizePolicy)
        self.IPLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.IPLineEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.IPLineEdit.setObjectName(_fromUtf8("IPLineEdit"))
        self.horizontalLayout.addWidget(self.IPLineEdit)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.portLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setReadOnly(True)
        self.portLineEdit.setObjectName(_fromUtf8("portLineEdit"))
        self.horizontalLayout.addWidget(self.portLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.traceLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.traceLineEdit.sizePolicy().hasHeightForWidth())
        self.traceLineEdit.setSizePolicy(sizePolicy)
        self.traceLineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.traceLineEdit.setObjectName(_fromUtf8("traceLineEdit"))
        self.horizontalLayout_2.addWidget(self.traceLineEdit)
        self.traceButton = QtGui.QPushButton(self.centralwidget)
        self.traceButton.setObjectName(_fromUtf8("traceButton"))
        self.horizontalLayout_2.addWidget(self.traceButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.workButton = QtGui.QPushButton(self.centralwidget)
        self.workButton.setObjectName(_fromUtf8("workButton"))
        self.verticalLayout_2.addWidget(self.workButton)
        self.drawButton = QtGui.QPushButton(self.centralwidget)
        self.drawButton.setObjectName(_fromUtf8("drawButton"))
        self.verticalLayout_2.addWidget(self.drawButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.timeScopeSpin = QtGui.QSpinBox(self.centralwidget)
        self.timeScopeSpin.setMinimum(20)
        self.timeScopeSpin.setMaximum(120)
        self.timeScopeSpin.setSingleStep(10)
        self.timeScopeSpin.setProperty("value", 30)
        self.timeScopeSpin.setObjectName(_fromUtf8("timeScopeSpin"))
        self.horizontalLayout_4.addWidget(self.timeScopeSpin)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.timeMultiSpin = QtGui.QSpinBox(self.centralwidget)
        self.timeMultiSpin.setMinimum(30)
        self.timeMultiSpin.setMaximum(200)
        self.timeMultiSpin.setSingleStep(10)
        self.timeMultiSpin.setProperty("value", 40)
        self.timeMultiSpin.setObjectName(_fromUtf8("timeMultiSpin"))
        self.horizontalLayout_4.addWidget(self.timeMultiSpin)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.List = QtGui.QTableWidget(self.centralwidget)
        self.List.setObjectName(_fromUtf8("List"))
        self.List.setColumnCount(0)
        self.List.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.List)
        self.infoViewer = QtGui.QTextBrowser(self.centralwidget)
        self.infoViewer.setMaximumSize(QtCore.QSize(500, 16777215))
        self.infoViewer.setObjectName(_fromUtf8("infoViewer"))
        self.horizontalLayout_6.addWidget(self.infoViewer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NodeSearch", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "BT客户端地址:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Trace文件路径:", None, QtGui.QApplication.UnicodeUTF8))
        self.traceButton.setText(QtGui.QApplication.translate("MainWindow", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.workButton.setText(QtGui.QApplication.translate("MainWindow", "提取所有检索过程", None, QtGui.QApplication.UnicodeUTF8))
        self.drawButton.setText(QtGui.QApplication.translate("MainWindow", "显示检索过程图", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "显示时间范围(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "显示时间精度", None, QtGui.QApplication.UnicodeUTF8))

